In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
import warnings
%matplotlib inline
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False
warnings.filterwarnings('ignore')

In [2]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [3]:
company = pd.read_csv('/Users/diadld3naver.com/Downloads/data.csv')

In [4]:
company.columns = company.columns.str.replace(' ','')

In [5]:
company["NetIncomeFlag"].value_counts()

1    6819
Name: NetIncomeFlag, dtype: int64

In [6]:
company=company.drop('NetIncomeFlag',axis=1)

In [7]:
company.head()



Bankrupt?  ROA(C)beforeinterestanddepreciationbeforeinterest  \
0          1                                           0.370594   
1          1                                           0.464291   
2          1                                           0.426071   
3          1                                           0.399844   
4          1                                           0.465022   

   ROA(A)beforeinterestand%aftertax  \
0                          0.424389   
1                          0.538214   
2                          0.499019   
3                          0.451265   
4                          0.538432   

   ROA(B)beforeinterestanddepreciationaftertax  OperatingGrossMargin  \
0                                     0.405750              0.601457   
1                                     0.516730              0.610235   
2                                     0.472295              0.601450   
3                                     0.457733              0.583541   
4                                     0.522298              0.598783   

   RealizedSalesGrossMargin  OperatingProfitRate  Pre-taxnetInterestRate  \
0                  0.601457             0.998969                0.796887   
1                  0.610235             0.998946                0.797380   
2                  0.601364             0.998857                0.796403   
3                  0.583541             0.998700                0.796967   
4                  0.598783             0.998973                0.797366   

   After-taxnetInterestRate  Non-industryincomeandexpenditure/revenue  \
0                  0.808809                                  0.302646   
1                  0.809301                                  0.303556   
2                  0.808388                                  0.302035   
3                  0.808966                                  0.303350   
4                  0.809304                                  0.303475   

   Continuousinterestrate(aftertax)  OperatingExpenseRate  \
0                          0.780985          1.256969e-04   
1                          0.781506          2.897851e-04   
2                          0.780284          2.361297e-04   
3                          0.781241          1.078888e-04   
4                          0.781550          7.890000e+09   

   Researchanddevelopmentexpenserate  Cashflowrate  \
0                                0.0      0.458143   
1                                0.0      0.461867   
2                         25500000.0      0.458521   
3                                0.0      0.465705   
4                                0.0      0.462746   

   Interest-bearingdebtinterestrate  Taxrate(A)  NetValuePerShare(B)  \
0                          0.000725         0.0             0.147950   
1                          0.000647         0.0             0.182251   
2                          0.000790         0.0             0.177911   
3                          0.000449         0.0             0.154187   
4                          0.000686         0.0             0.167502   

   NetValuePerShare(A)  NetValuePerShare(C)  \
0             0.147950             0.147950   
1             0.182251             0.182251   
2             0.177911             0.193713   
3             0.154187             0.154187   
4             0.167502             0.167502   

   PersistentEPSintheLastFourSeasons  CashFlowPerShare  \
0                           0.169141          0.311664   
1                           0.208944          0.318137   
2                           0.180581          0.307102   
3                           0.193722          0.321674   
4                           0.212537          0.319162   

   RevenuePerShare(Yuan¥)  OperatingProfitPerShare(Yuan¥)  \
0                0.017560                        0.095921   
1                0.021144                        0.093722   
2                0.005944                        0.092338   
3                0.014368          

In [75]:
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
over = SMOTE()
SDS=StandardScaler()

X = company.drop('Bankrupt?',axis=1)
y = company['Bankrupt?']
X,y = over.fit_resample(X,y)

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)


In [77]:
SDS.fit(X_train)
SDS_train=SDS.transform(X_train)
SDS_test=SDS.transform(X_test)

In [109]:
from sklearn.decomposition import PCA

pca = PCA(n_components=60)
X_train = pca.fit_transform(SDS_train)
X_test = pca.transform(SDS_test)

In [110]:
X_train.shape, X_test.shape

((9898, 60), (3300, 60))

In [111]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(solver='lbfgs',max_iter=1000).fit(X_train,y_train)
logreg.fit(X_train,y_train)

y_log=logreg.predict(X_test)
kfold = KFold(n_splits=10, shuffle = True, random_state=0)
scores = cross_val_score(logreg ,X,y ,cv=kfold)


print("훈련 세트 점수: {:.3f}".format(logreg.score(X_train,y_train)))
print("테스트 세트 점수: {:.3f}\n".format(logreg.score(X_test,y_test)))

print("Confusion Matrix\n",confusion_matrix(y_log,y_test))
print("\nClassification Report\n\n",classification_report(y_log,y_test))

print('교차 검증별 정확도:\n',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

훈련 세트 점수: 0.906
테스트 세트 점수: 0.903

Confusion Matrix
 [[1479  133]
 [ 187 1501]]

Classification Report

               precision    recall  f1-score   support

           0       0.89      0.92      0.90      1612
           1       0.92      0.89      0.90      1688

    accuracy                           0.90      3300
   macro avg       0.90      0.90      0.90      3300
weighted avg       0.90      0.90      0.90      3300

교차 검증별 정확도:
 [0.6023 0.5939 0.6061 0.6098 0.622  0.6485 0.6212 0.6167 0.6035 0.5747]
평균 검증 정확도: 0.6099


In [112]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)

y_de=tree.predict(X_test)
kfold = KFold(n_splits=10, shuffle = True, random_state=0)
scores = cross_val_score(tree ,X,y ,cv=kfold)


print("훈련 세트 점수: {:.3f}".format(tree.score(X_train,y_train)))
print("테스트 세트 점수: {:.3f}\n".format(tree.score(X_test,y_test)))

print("Confusion Matrix\n",confusion_matrix(y_de,y_test))
print("\nClassification Report\n\n",classification_report(y_de,y_test))

print('교차 검증별 정확도:\n',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

훈련 세트 점수: 0.894
테스트 세트 점수: 0.883

Confusion Matrix
 [[1423  142]
 [ 243 1492]]

Classification Report

               precision    recall  f1-score   support

           0       0.85      0.91      0.88      1565
           1       0.91      0.86      0.89      1735

    accuracy                           0.88      3300
   macro avg       0.88      0.88      0.88      3300
weighted avg       0.89      0.88      0.88      3300

교차 검증별 정확도:
 [0.9083 0.8909 0.9197 0.8902 0.9045 0.8924 0.9023 0.9129 0.9181 0.8878]
평균 검증 정확도: 0.9027


In [113]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=3, random_state=0)
forest.fit(X_train, y_train)

y_fo=forest.predict(X_test)
kfold = KFold(n_splits=10, shuffle = True, random_state=0)
scores = cross_val_score(forest ,X,y ,cv=kfold)


print("훈련 세트 점수: {:.3f}".format(forest.score(X_train,y_train)))
print("테스트 세트 점수: {:.3f}\n".format(forest.score(X_test,y_test)))

print("Confusion Matrix\n",confusion_matrix(y_fo,y_test))
print("\nClassification Report\n\n",classification_report(y_fo,y_test))

print('교차 검증별 정확도:\n',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

훈련 세트 점수: 0.990
테스트 세트 점수: 0.947

Confusion Matrix
 [[1539   48]
 [ 127 1586]]

Classification Report

               precision    recall  f1-score   support

           0       0.92      0.97      0.95      1587
           1       0.97      0.93      0.95      1713

    accuracy                           0.95      3300
   macro avg       0.95      0.95      0.95      3300
weighted avg       0.95      0.95      0.95      3300

교차 검증별 정확도:
 [0.9659 0.9583 0.9659 0.9667 0.9568 0.9644 0.9735 0.9652 0.9674 0.9492]
평균 검증 정확도: 0.9633


In [108]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=10, random_state=0)
forest.fit(X_train, y_train)

y_fo=forest.predict(X_test)
kfold = KFold(n_splits=10, shuffle = True, random_state=0)
scores = cross_val_score(forest ,X,y ,cv=kfold)


print("훈련 세트 점수: {:.3f}".format(forest.score(X_train,y_train)))
print("테스트 세트 점수: {:.3f}\n".format(forest.score(X_test,y_test)))

print("Confusion Matrix\n",confusion_matrix(y_fo,y_test))
print("\nClassification Report\n\n",classification_report(y_fo,y_test))

print('교차 검증별 정확도:\n',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

훈련 세트 점수: 0.999
테스트 세트 점수: 0.971

Confusion Matrix
 [[1601   30]
 [  65 1604]]

Classification Report

               precision    recall  f1-score   support

           0       0.96      0.98      0.97      1631
           1       0.98      0.96      0.97      1669

    accuracy                           0.97      3300
   macro avg       0.97      0.97      0.97      3300
weighted avg       0.97      0.97      0.97      3300

교차 검증별 정확도:
 [0.9773 0.978  0.9803 0.972  0.9811 0.9795 0.9864 0.9818 0.981  0.9704]
평균 검증 정확도: 0.9788
